Add unit tests for org.zaproxy.zap.utils.ByteBuilder
Diffblue-benchmarks/Zaproxy-zaproxy pull request #1
Opened 2019-06-14 16:49 UTC by Braavos96

I've analysed your codebase and noticed that `org.zaproxy.zap.utils.ByteBuilder` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

2019-06-17 10:53 UTC, petersear requested changes

2019-06-17 10:53 UTC, petersear commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +    public void testEnsureSize() {
There is no ensureSize() method so this should probably be testSize()?

2019-06-17 10:53 UTC, petersear commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        thrown.expect(ArrayIndexOutOfBoundsException.class);
Insert blank line between assert and exception sections.

2019-06-17 10:53 UTC, petersear commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        byteBuilder.append(1234567890123456789l);
It's common to use `L` to denote `long` and avoid confusion with `1`

2019-06-17 10:53 UTC, petersear commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        byteBuilder.appendSpecial(1234567890123456789l, 3, true);
`l` -> `L`

2019-06-17 10:53 UTC, petersear commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        byteBuilder.appendSpecial(-1234567890123456789l, 3, true);
`l` -> `L`

2019-06-18 09:32 UTC, Braavos96 commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +    public void testEnsureSize() {
I was going for creativity there :p 
Done

2019-06-18 09:32 UTC, Braavos96 commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        thrown.expect(ArrayIndexOutOfBoundsException.class);
Done

2019-06-18 09:32 UTC, Braavos96 commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        byteBuilder.append(1234567890123456789l);
Done

2019-06-18 09:32 UTC, Braavos96 commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        byteBuilder.appendSpecial(1234567890123456789l, 3, true);
Done

2019-06-18 09:32 UTC, Braavos96 commented on zap/src/test/java/org/zaproxy/zap/utils/ByteBuilderTest.java
> +        byteBuilder.appendSpecial(-1234567890123456789l, 3, true);
Done

2019-06-18 09:41 UTC, petersear approved these changes

2019-06-19 10:28 UTC, freddytuxworth approved these changes

2019-06-19 11:18 UTC, closed without merging